//To store the identity of a user a token is generated by jwt, it consist of 3 parts=> header,payload,secretKey

const jwt = require("jsonwebtoken");

module.exports= (user) => {
  return jwt.sign(
    {
      _id: user._id,
      name: user.firstname,
      email: user.email,
    },
    //when a request is sent from client side to server side the jsonwebtoken verifies the user using the secret key
    "secretKey",
    {
      expiresIn: "2d",
    }
  );
};

